org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# ---------------------------------------------------------------
# کلیدهای تپسل
# ---------------------------------------------------------------
TAPSELL_APP_ID=leqncsmjpekcpjgmacobftjhbegfccfpgsqbneclnojshqsbpmpdeojqncepatrlgetsik
TAPSELL_ZONE_INTERSTITIAL=6aa5ca2b1f07c00619f45129
TAPSELL_ZONE_BANNER=6aa5cae6796a202335abbc77
